Homework 2 LAB
PAIR PROGRAMMING: We are going to allow pair programming for this lab. You will work in groups of one or two. (No groups >2). You will get an F for the course if your group plagiarizes or copies somebody else’s work or some other group’s work. You can discuss anything ONLY with your pair team member. Members in the pair have to work on the entire problem and submit your own notebooks, and submission

Problem -  Design and develop a Machine learning model that can help in making predictions that may be useful for doctors and healthcare providers to predict potential heart disease cases early on. Use below dataset to predict which patients are most likely to suffer from a heart disease in the near future using the features given.

Dataset - Heart disease Prediction dataset

Download Heart disease Prediction dataset

Dataset Description-

1. age
2. sex
3. chest pain type (4 values)
4. resting blood pressure
5. serum cholestoral in mg/dl
6. fasting blood sugar > 120 mg/dl
7. resting electrocardiographic results (values 0,1,2)
8. maximum heart rate achieved
9. exercise induced angina
10. oldpeak = ST depression induced by exercise relative to rest
11. the slope of the peak exercise ST segment
12. number of major vessels (0-3) colored by flourosopy
13. thal: 0 = normal; 1 = fixed defect; 2 = reversable defect

14. target    Have disease or not (1 = yes; 0 = no)

 

The steps in this notebook should include:

    Data Exploration: Understanding the dataset and key features.
    
    Data Preprocessing: Cleaning the data, handling missing values, and normalizing features.
    
    Modeling: Implementing and evaluating machine learning model - Logistic Regression
    
    Evaluation: Evaluate your model 


###     Data Exploration: Understanding the dataset and key features.

In [2]:
import matplotlib.pyplot as plt

In [3]:
import seaborn as sns

In [4]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
from sklearn import linear_model

In [7]:
from sklearn import datasets

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
from pydataset import data

In [10]:
heart_data = pd.read_csv('heart.csv')

In [11]:
heart_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [12]:
heart_data.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [13]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [14]:
heart_data.values

array([[52.,  1.,  0., ...,  2.,  3.,  0.],
       [53.,  1.,  0., ...,  0.,  3.,  0.],
       [70.,  1.,  0., ...,  0.,  3.,  0.],
       ...,
       [47.,  1.,  0., ...,  1.,  2.,  0.],
       [50.,  0.,  0., ...,  0.,  2.,  1.],
       [54.,  1.,  0., ...,  1.,  3.,  0.]])

In [15]:
heart_data.nunique()

age          41
sex           2
cp            4
trestbps     49
chol        152
fbs           2
restecg       3
thalach      91
exang         2
oldpeak      40
slope         3
ca            5
thal          4
target        2
dtype: int64

In [16]:
heart_data.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [17]:
features_cols = [col for col in heart_data.columns if col != 'target']

In [18]:
features_cols

['age',
 'sex',
 'cp',
 'trestbps',
 'chol',
 'fbs',
 'restecg',
 'thalach',
 'exang',
 'oldpeak',
 'slope',
 'ca',
 'thal']

In [19]:
labels = heart_data.target

In [20]:
labels

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [21]:
X= heart_data[features_cols]

In [22]:
y = heart_data.target

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=23)

In [25]:
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
37    59    1   0       138   271    0        0      182      0      0.0   
541   44    1   2       140   235    0        0      180      0      0.0   
574   60    1   0       125   258    0        0      141      1      2.8   
597   38    1   2       138   175    0        1      173      0      0.0   
312   70    1   2       160   269    0        1      112      1      2.9   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
950   67    1   0       160   286    0        0      108      1      1.5   
969   52    1   1       120   325    0        1      172      0      0.2   
40    65    0   2       160   360    0        0      151      0      0.8   
742   63    1   0       130   330    1        0      132      1      1.8   
595   61    1   0       148   203    0        1      161      0      0.0   

     slope  ca  thal  
37       2   0     2  
541      2   0     2  
574      1   1     3  
597      2   4     2  
312      1   1     3  
..     ...  ..   ...  
950      1   3     2  
969      2   0     2  
40       2   0     2  
742      2   3     3  
595      2   1     3  

[820 rows x 13 columns]

Data Preprocessing: Cleaning the data, handling missing values, and normalizing features.

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
scaler = StandardScaler()

In [28]:
X_train_scaled = scaler.fit_transform(X_train)

In [29]:
X_test_scaled = scaler.transform(X_test)

In [30]:
from sklearn.linear_model import LogisticRegression

In [32]:
logreg_scaled = LogisticRegression(random_state=23).fit(X_train_scaled, y_train) 

In [33]:
logreg_scaled.score(X_train_scaled, y_train)

0.85

In [34]:
logreg_scaled.score(X_test_scaled, y_test)

0.8731707317073171

In [40]:
logreg = LogisticRegression(max_iter=900, random_state=23)

In [41]:
logreg.fit(X_train, y_train)

LogisticRegression(max_iter=900, random_state=23)

In [42]:
logreg.score(X_test, y_test)

0.8731707317073171

In [43]:
logreg.score(X_train, y_train)

0.848780487804878

In [44]:
y_pred = logreg.predict(X_test)

In [48]:
y_pred_scaled = logreg.predict(X_test)

In [49]:
from sklearn import metrics

In [50]:
cnf_matrix_scaled = metrics.confusion_matrix(y_test, y_pred_scaled)

In [51]:
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)

In [53]:
cnf_matrix_scaled

array([[82, 18],
       [ 8, 97]])

In [52]:
cnf_matrix

array([[82, 18],
       [ 8, 97]])