# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction

In [70]:
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 

In [73]:
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

In [76]:
data = np.array([1,2,3,4,5])

In [78]:
print(data)

[1 2 3 4 5]


In [80]:
print(len(data))

5


In [82]:
print(type(data))

<class 'numpy.ndarray'>


In [84]:
print(data.shape)

(5,)


### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

In [87]:
arr = np.array([10, 20, 30, 40])

In [89]:
print(arr[0])

10


In [91]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [93]:
print(arr[1:5])

[2 3 4 5]


In [94]:
import numpy as np
arr = np.array(['kiwi', 'berry', 'pear'])
print(np.sort(arr))

['berry' 'kiwi' 'pear']


### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:

In [99]:
arr = np.array([3, 2, 14, 9, 10, 12])

In [101]:
print("index value of 9 is: ", np.where(arr == 9)[0])

index value of 9 is:  [3]


### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

In [61]:
arr1 = np.array([9, 5, 8])


In [63]:
arr2 = np.array([55, 89, 76])

In [65]:
arr = np.concatenate((arr1, arr2))

In [67]:
print(arr) 

[ 9  5  8 55 89 76]
