# Scikit Learn Exercise   AI240 - 10459
## Instructor - Dr. Uma Gajendragadkar

## Exercise 1 - 
First install Numpy Library (if it's not already installed) as it is required by Scikit Learn Library.

!pip install numpy

If already not installed, then  install Scikit Learn Library using below instruction on Jupyter Notebook

!pip install scikit-learn

Once the installation is complete, you can verify whether Scikit-learn is installed or not by typing the following command:

pip show scikit-learn

## Exercise 2 - 
First import pandas and numpy with below statements
import numpy as np
import pandas as pd

Import the scikit Learn Library datasets with below statement

import sklearn

from sklearn import datasets

## Exercise 3 - 
Load default datsets - the iris dataset with below statetments.

iris = datasets.load_iris()

The Iris dataset, a classic in machine learning, is a dataset of 150 iris flower measurements, including sepal and petal length and width, used for classification tasks, and is readily available within the scikit-learn library.

A dataset is a dictionary-like object that holds all the data and some metadata about the data.The variables of data are called its features. They are also known as predictors or attributes.

Feature matrix − It is the collection of features, in case there are more than one.

Feature Names − list of names of the features.

Response − It is the output variable that basically depends upon the feature variables. They are also known as target, label or output.

Response Vector − It is used to represent response column. Generally, we have just one response column.

Target Names − It represent the possible values taken by a response vector.

## Exercise 4 - 
Lets's use IRIS dataset and execute below lines of code and check the output.

from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data

y = iris.target

feature_names = iris.feature_names

target_names = iris.target_names

print("Feature names:", feature_names)

print("Target names:", target_names)

print("\nFirst 10 rows of X:\n", X[:10])


## Exercise 5 - 
Splitting the dataset
Split the dataset into two pieces-a training set and a testing set. Use the training set to train the model and testing set to test the model. Execute below lines of code to split the data into 80:20 ratio . It means 80% data is training data and 20% as testing data.

print(X_train.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

print(X_test.shape)

print(y_train.shape)

print(y_test.shape)

## Exercise 6 - 
Train the Model
Use our dataset to train some prediction-model. Scikit-learn has wide range of Machine Learning (ML) algorithms.

Here, we are going to use KNN (K nearest neighbors) classifier for sake of learning the scikit Library. We are going to learn classification in detail in coming weeks. Below lines of code are to be executed and are used to make you understand the implementation. 


from sklearn.neighbors import KNeighborsClassifier

from sklearn import metrics

classifier_knn = KNeighborsClassifier(n_neighbors = 5)

classifier_knn.fit(X_train, y_train)

y_pred = classifier_knn.predict(X_test)

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))



In [1]:
!pip install numpy


In [3]:
!pip install scikit-learn


In [5]:
pip show scikit-learn

Name: scikit-learn
Version: 1.3.2
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author: 
Author-email: 
License: new BSD
Location: /Users/matt/miniforge3/lib/python3.10/site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: mapclassify
Note: you may need to restart the kernel to use updated packages.


# Scikit Learn Exercise   AI240 - 10459
## Instructor - Dr. Uma Gajendragadkar

## Exercise 1 - 

First install Numpy Library (if it's not already installed) as it is required by Scikit Learn Library.

In [ ]:
!pip install numpy

If already not installed, then  install Scikit Learn Library using below instruction on Jupyter Notebook

In [ ]:
!pip install scikit-learn

Once the installation is complete, you can verify whether Scikit-learn is installed or not by typing the following command:

In [ ]:
pip show scikit-learn

## Exercise 2 - 
First import pandas and numpy with below statements

In [7]:
import numpy as np
import pandas as pd

Import the scikit Learn Library datasets with below statement

In [9]:
import sklearn

from sklearn import datasets

## Exercise 3 - 
Load default datsets - the iris dataset with below statetments.

In [13]:
iris = datasets.load_iris()

The Iris dataset, a classic in machine learning, is a dataset of 150 iris flower measurements, including sepal and petal length and width, used for classification tasks, and is readily available within the scikit-learn library.

A dataset is a dictionary-like object that holds all the data and some metadata about the data.The variables of data are called its features. They are also known as predictors or attributes.

Feature matrix − It is the collection of features, in case there are more than one.

Feature Names − list of names of the features.

Response − It is the output variable that basically depends upon the feature variables. They are also known as target, label or output.

Response Vector − It is used to represent response column. Generally, we have just one response column.

Target Names − It represent the possible values taken by a response vector.

## Exercise 4 - 
Lets's use IRIS dataset and execute below lines of code and check the output.

In [61]:
from sklearn.datasets import load_iris

In [63]:
iris = load_iris()

In [65]:
X = iris.data

In [67]:
y = iris.target

In [69]:
feature_names = iris.feature_names

In [71]:
target_names = iris.target_names

In [73]:
print("Feature names:", feature_names)

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [75]:
print("Target names:", target_names)

Target names: ['setosa' 'versicolor' 'virginica']


In [77]:
print("\nFirst 10 rows of X:\n", X[:10])


First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


## Exercise 5 - 
Splitting the dataset
Split the dataset into two pieces-a training set and a testing set. 
Use the training set to train the model and testing set to test the model. 
Execute below lines of code to split the data into 80:20 ratio . 
It means 80% data is training data and 20% as testing data.

In [79]:
print(X_train.shape)

(120, 4)


In [81]:
from sklearn.model_selection import train_test_split

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [85]:
print(X_test.shape)

(30, 4)


In [87]:
print(y_train.shape)

(120,)


In [89]:
print(y_test.shape)

(30,)


## Exercise 6 - 
Train the Model
Use our dataset to train some prediction-model. 
Scikit-learn has wide range of Machine Learning (ML) algorithms.

Here, we are going to use KNN (K nearest neighbors) classifier for sake of learning the scikit Library. 
We are going to learn classification in detail in coming weeks. 
Below lines of code are to be executed and are used to make you understand the implementation. 

In [91]:
from sklearn.neighbors import KNeighborsClassifier

In [93]:
from sklearn import metrics

In [99]:
classifier_knn = KNeighborsClassifier(n_neighbors = 5)

In [103]:
classifier_knn.fit(X_train, y_train)

KNeighborsClassifier()

In [105]:
y_pred = classifier_knn.predict(X_test)

In [107]:
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0
